inner_entities = {
    "issues": [
        "label",
        "status",
        "title",
        "author",
        "assignee",
        "description",
        "created_at",
        "updated_at",
        "milestone",
    ],
    "pull request": [
        "status",
        "author",
        "assignee",
        "title",
        "created_at",
        "updated_at",
        "merged_at",
        "milestone",
    ],
    "user": ["repos", "name", "contributions"],
    "repo": [
        "issues",
        "pull requests",
        "contributors",
        "languages",
        "commits",
        "title",
        "created_at",
        "updated_at",
    ],
    "commit": ["message", "author", "date", "hash"],
}
